### ISSUE TITLE
MetaCall Core is not functioning

### ISSUE THREAD

**Issue by i-am-yuvi** [metacall/landing-page#9]
The GitHub pages deployed for MetaCall Core is not working.

<img width="1280" alt="Screenshot 2024-01-22 at 12 54 19 PM" src="https://github.com/metacall/landing-page/assets/92994932/653fda64-35ee-415d-81d9-3801af9c6de7">

**Comment by viferga** [comment]
Thanks for reporting it, I am going to review it.

**Comment by viferga** [comment]
@i-am-yuvi Solved: https://core.metacall.io
